[package]
name = "ammonia"
version = "1.0.0"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html", "security", "xss" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/notriddle/ammonia"
categories = [ "web-programming", "text-processing" ]

[dependencies]
html5ever = "0.21"
maplit = "1.0"
matches = "0.1.6"
tendril = "0.4"
url = "1.6"
lazy_static = "0.2"

[dev-dependencies]
version-sync = "0.4"
