[package]
name = "ammonia"
version = "3.0.0"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html", "security", "xss" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/rust-ammonia/ammonia"
categories = [ "web-programming", "text-processing" ]
edition = "2018"

[dependencies]
html5ever = "0.24"
maplit = "1.0"
matches = "0.1.6"
tendril = "0.4"
url = "2"
lazy_static = "1.3"

[dev-dependencies]
version-sync = "0.7"
env_logger = "0.6.1"
